# Project details
sonar.projectKey=3-tier-frontend-test
sonar.projectName=3-tier-frontend-test

# Source code configuration
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js

# Language and framework settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Host details
sonar.host.url=http://10.101.7.154:9000
sonar.login=sqa_7f3b076d381320fef210714a1f49a390b5b9e357
